### PR TITLE
Fix array to single element

### LINKED ISSUE #23: common.type in a state should not be an array
Set to typeof value or first element

### PR DESCRIPTION
**Pull request by gaudes**
Fix #23

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -81,6 +81,19 @@ export function buildObject(adapterInstance: ioBroker.Adapter, options: BuildObj
 		definition.common.desc = options.description;
 	}
 
+	if (definition.type === "state"){
```
Comment (AlCalzone) [inline src/main.ts:84]: I would leave a comment above this block explaning what this is supposed to do:
The templates may contain arrays for some values that are no arrays in ioBroker. We find them and pin them to a single value.

File: src/main.ts [hunk 2]
```diff
@@ -81,6 +81,19 @@ export function buildObject(adapterInstance: ioBroker.Adapter, options: BuildObj
...
+		if (Array.isArray(definition.common.type)){
+			if (options.value && definition.common.type.includes(typeof(options.value)) === true){
```
Comment (AlCalzone) [inline src/main.ts:86]: `=== true` is useless for a method that returns a boolean

File: src/main.ts [hunk 3]
```diff
@@ -81,6 +81,19 @@ export function buildObject(adapterInstance: ioBroker.Adapter, options: BuildObj
...
+				definition.common.type = typeof(options.value) as ioBroker.CommonType;
```
Comment (AlCalzone) [inline src/main.ts:87]: `typeof` and `ioBroker.CommonType` are not the same.
* `typeof [] === "object"`, but the common.type would be `"array"`
* `typeof {} === "object"`, but the common.type would be `"object"`
* `typeof null === "object"`, but the common.type could be any one of the allowed types

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: src/main.ts [hunk 4]
```diff
@@ -47,6 +47,35 @@ function ensureNamespace(namespace: string, objectId: string): string {
...
+	}
+}
+
+function selectTypefromArray(value: any, AllowedTypes: ioBroker.CommonType[]): ioBroker.CommonType{
+	const TypeOfValue = getTypefromValue(value) as ioBroker.CommonType;
+	if (AllowedTypes.includes(TypeOfValue)){
+		return TypeOfValue;
+	}else{
+		throw "Invalid type of value"
+	}
```
Comment (AlCalzone) [inline src/main.ts:76]: Are we sure that the value is never null or undefined here? If so, LGTM

File: src/main.ts [hunk 5]
```diff
@@ -47,6 +47,35 @@ function ensureNamespace(namespace: string, objectId: string): string {
...
+			return "boolean";
+	}
+}
+
+function selectTypefromArray(value: any, AllowedTypes: ioBroker.CommonType[]): ioBroker.CommonType{
+	const TypeOfValue = getTypefromValue(value) as ioBroker.CommonType;
+	if (AllowedTypes.includes(TypeOfValue)){
+		return TypeOfValue;
+	}else{
+		throw "Invalid type of value"
```
Comment (AlCalzone) [inline src/main.ts:75]: Maybe we should say which type was selected and which types are allowed?

File: src/main.ts [hunk 6]
```diff
@@ -47,6 +47,35 @@ function ensureNamespace(namespace: string, objectId: string): string {
...
+		case "object":
+			// Handle typeof [] === "object"
+			if (Array.isArray(value)){
+				return "array";
+			// Handle typeof {} === "object"
+			}else if(Object.prototype.toString.call(value) === "[object Object]"){
+				return "object";
+			// typeof null === "object"
+			}
+		case "number":
```
Comment (AlCalzone) [inline src/main.ts:61]: you should add a `return;` above this line or `null` will always fall through to the `number` case

Comment (AlCalzone) [reply src/main.ts:61]: nevermind, you're not calling this with `null`. I keep getting confused by this.

**Review by AlCalzone — APPROVED** [review]
