### PR TITLE
Issue#36 cleanup and fix roles and prepare for unit check

### LINKED ISSUE #36: Cleanup and fix roles and prepare for unit check
Some entries are incorrect in roles, for example:

"sensor.noise":{
        "desc":"Noise sensor",
        "type":"boolean",
        "read":true,
        "write":false,
        "unit":"dB"
    },

Also roles should be prepared for unit check.

Unit should be:
- a string for a single unit
- an array for multiple possible units
- null when it's forbidden to set an unit

### PR DESCRIPTION
**Pull request by gaudes**
Fix #36

### CODE REVIEW

File: src/lib/roles.ts [hunk 1]
```diff
@@ -196,7 +237,8 @@ export const roles_definition = validateRoles({
 			"0":"CLOSED",
 			"1":"TILTED",
 			"2":"OPEN"
-		}
+		},
+		"unit": "null"
```
Comment (AlCalzone) [inline src/lib/roles.ts:241]: Shouldn't this be `null`, not `"null"`?

File: src/lib/roles.ts [hunk 2]
```diff
@@ -709,8 +804,46 @@ export const roles_definition = validateRoles({
...
+			"number"
+		],
+		"read":true,
+		"write":true,
+		"states":{
+			"0":"AUTO",
+			"1":"fast",
+			"2":"medium",
+			"3":"slow",
+			"4":"turbo",
```
Comment (AlCalzone) [inline src/lib/roles.ts:841]: Is the original enumeration really that chaotic? Maybe we need to change the specs/docs :D

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: src/lib/roles.ts (hunk 1 above)
Comment (gaudes) [reply src/lib/roles.ts:241]: Null is now allowed due to Typescript checking :-)

"Type 'null' is not assignable to type 'string | string[] | undefined'.

Anyway, we need a value of unit against which we can check if it's not allowed to set a unit.

We can choose a more descriptive name, e.g. "unallowed"

File: src/lib/roles.ts (hunk 2 above)
Comment (gaudes) [reply src/lib/roles.ts:841]: Official documentation:
```
level.mode.work - Enumeration of AUTO, FAST, MEDIUM, SLOW, TURBO. Optional state.
```
Documentation is not straight in some point. One more example:

```
Levels (numbers, read-write)
With levels you can control or set some number value.
level.co2 - 0-100% ait quality
```

Didn't know that I can choose the co2-level :)

Comment (AlCalzone) [reply src/lib/roles.ts:841]: Hmm, IMO that documentation doesn't really imply any particular order. Let's sort it in a sensible way.

> Didn't know that I can choose the co2-level :)

LOL

File: src/lib/roles.ts (hunk 1 above)
Comment (AlCalzone) [reply src/lib/roles.ts:241]: > "Type 'null' is not assignable to type 'string | string[] | undefined'.

Then let's update our definition for the interface. I'd be fine with some more descriptive name instead of `null`.

Comment (gaudes) [reply src/lib/roles.ts:241]: When we choose a more descriptive string instead of null we don't need to update the definition of the interface.

Should we choose "unallowed" ?

File: src/lib/roles.ts (hunk 2 above)
Comment (gaudes) [reply src/lib/roles.ts:841]: Gona set the order to AUTO, slow, medium, fast, turbo
That makes more sense.

File: src/lib/roles.ts (hunk 1 above)
Comment (AlCalzone) [reply src/lib/roles.ts:241]: `"disallowed"` or `"forbidden"` sound better IMO

Comment (gaudes) [reply src/lib/roles.ts:241]: "forbidden" is perfect.
Gona change and create a new commit.

**Review by AlCalzone — APPROVED** [review]
