### PR TITLE
Remove module exports

### LINKED ISSUE #14: Incorrect module.exports in object_attributes
Line could be removed:

module.exports = { objectCommonSchemas, commonAttributes };

### PR DESCRIPTION
**Pull request by gaudes**
Fix #14

### CODE REVIEW

File: src/lib/object_attributes.ts [hunk 1]
```diff
@@ -674,6 +674,4 @@ export const commonAttributes = validateCommonAttributes({
 		"desc": "Host on which the instance is running.",
 		"attrType": "string"
 	}*/
-});
-
-module.exports = { objectTypes: objectCommonSchemas, commonAttributes };
```
Comment (AlCalzone) [inline src/lib/object_attributes.ts:679]: Did you rename the usage sites aswell?

**Comment by gaudes** [comment]
In the usage it was already named so:

https://github.com/gaudes/iobroker-object-helper/blob/0726babd870911441594d2e93e4754d68fa0f6f4/src/main.ts#L188
